services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsh-lw-ppocr-web
    ports:
      - "${HOST_PORT:-3003}:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./:/app
  # test-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: dsh-lw-ppocr-test
  #   command: node test/test-plugin.js
  #   volumes:
  #     - ./:/app
